### ISSUE TITLE
AttemptsSpent is doubling

### ISSUE THREAD

**Issue by css3ninja** [adaptlearning/adapt-contrib-assessment#138]
Looks like when I have 4 attempts for an assessment instead of infinity. Each time it uses up 2 attempts when I complete the assessment. My thinking is the problem is to do with the _onBlockCompleted & _this._checkAssessmentComplete(); is being dublicated also by _onQuestionCompleted...

_onBlockCompleted(blockModel, value) {
    if (value === false) return;
    const questionModels = blockModel.findDescendantModels('question');
    questionModels.forEach(questionModel => {
      this._onQuestionCompleted(questionModel, value);
    });
    if (!blockModel.get('_isInteractionComplete')) return;
    **_this._checkAssessmentComplete();_**
  },

  _onQuestionCompleted(questionModel, value) {
    if (value === false) return;
    if (!questionModel.get('_isInteractionComplete')) return;

    let numberOfQuestionsAnswered = this.get('_numberOfQuestionsAnswered');
    numberOfQuestionsAnswered++;
    this.set('_numberOfQuestionsAnswered', numberOfQuestionsAnswered);

    this._updateQuestionsState();
    Adapt.assessment.saveState();

    this._checkAssessmentComplete();
  },

**Comment by oliverfoster** [comment]
@css3ninja could you check the above pr please?

**Comment by css3ninja** [comment]
@oliverfoster Thanks for your help Oliver! I tested it and is working now

**Comment by oliverfoster** [comment]
Now worries, thanks you. I saw your approval on the pr. It's queued for release at the moment  :+1:

**Comment by oliverfoster** [comment]
Now worries, thanks you. I saw your approval on the pr. It's queued for release at the moment  :+1:
