### ISSUE TITLE
assessment restoration/completion

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-assessment#151]
### Subject of the issue/enhancement/features
It is possible to return to an assessment which has rendered a results component without any feedback.

This seems to be because the assessment is not setting `_isAssessmentComplete: true` when all questions have been answered but trickle hasn't yet been clicked. Without clicking the trickle button, the block is not set to complete and therefore the assessment doesn't update the saved state.

### Your environment
* Adapt framework: 5.18.6

### Steps to reproduce
 * Assessment must be set to `"_isResetOnRevisit": false`. Trickle needs to configured with the button enabled.
 * Complete all questions. Exit before clicking the trickle button on final question.
 * Relaunch and access the assessment. You can scroll down to the results, but no feedback is rendered as the relevant events have not been triggered.

**Comment by oliverfoster** [comment]
This shouldn't matter as assessment is complete when all of the expected questions are complete: 
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L301-L308
Modified here https://github.com/adaptlearning/adapt-contrib-assessment/commit/55410b4b3730e27ba266dce67b4929ca96cbc85e and https://github.com/adaptlearning/adapt-contrib-assessment/commit/ca5db33503bca0de83284890b853b13dd9dd8511

With the exception of when branching is enable. Fix for that is here https://github.com/adaptlearning/adapt-contrib-branching/pull/22/files and https://github.com/adaptlearning/adapt-contrib-assessment/commit/55410b4b3730e27ba266dce67b4929ca96cbc85e
