### ISSUE TITLE
Assessment banks not used

### ISSUE THREAD

**Issue by lars-moch** [adaptlearning/adapt-contrib-assessment#157]
I updated my test Adapt AT server (AT: v0.10.5, FW: v5.18.5) with the new v4.6.0 "adapt-contrib-assessment" extension.

The course I tested is just a page with one article with an assessment having 7 MCQ questions.
- The questions are assigned to 3 banks (with 3, 2, and 2 questions).
- The draw is done using this split: "1,1,1".

But with the new assessment version, I get all 7 questions every time.

I noticed this when I did a little debugging:
- In the assessment model, the "_setupAssessmentData" function the "shouldResetAssessment" variable is always false, which in turn means that the "_setupBankedAssessment" function is never called.
- "shouldResetAssessment" is false because "shouldResetOnRevisit" is false, "state.isPass" is undefined, "hasAttemptsLeft" is false, and "force" is undefined.

I would have expected the "_setupBankedAssessment" function to be called on the first visit.

**Comment by ethan-lp** [comment]
Hi @oliverfoster, would it be appropriate to remove the nested if here; to its own line and perform the check for enabled banks independent of `shouldResetAssessment` ?
https://github.com/adaptlearning/adapt-contrib-assessment/blob/4d0471acd8f8e7bf5121312a0c17545470990902/js/adapt-assessmentArticleModel.js#L142

**Comment by oliverfoster** [comment]
Sorry @ethan-lp I missed your comment. No I think bank setup should only happen inside shoudlResetAssessment, otherwise it'll overwrite existing assessment attempts with new questions unnecessarily. 

I hope I understood that correctly?

**Comment by ethan-lp** [comment]
No worries @oliverfoster and I get what you mean too thanks for explaining that too.
