### ISSUE TITLE
assessments "soft" reset

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-assessment#160]
When an assessment is set to use a "soft" reset on its question models, the assessment and assessments models both reset their completion properties, but the `_assessmentState` saved in https://github.com/adaptlearning/adapt-contrib-core/blob/aacbc90cc7eeedaea649270303a695c9fc7f45a0/js/tracking.js retains the completion for use in its completion checks. However, if a course contains multiple assessments, and one is "soft" reset before the other is completed, the tracking will not have saved the `_assessmentState` to be used later, meaning any reset assessment needs to be retaken.

**Comment by oliverfoster** [comment]
Update:

Assessment 1 is completed then soft reset, assessment 2 is then completed. Course isn't complete.
If you complete them both first and then soft reset it works fine.
