### ISSUE TITLE
missing `_randomisation` config error

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-assessment#161]
If the '_randomisation` config is missing from the assessment article, and question banks are disabled, the following line creates an error:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L146

**Comment by oliverfoster** [comment]
duplicate of https://github.com/adaptlearning/adapt_framework/issues/3287
