### ISSUE TITLE
language constants

### ISSUE THREAD

**Issue by alexkash** [adaptlearning/adapt-contrib-assessment#177]
### Subject of the issue/enhancement/features
Hi!
I want to translate the interface into Ukrainian and do not understand how to do it. I'm not a programmer, but I can edit the translation file. :) Please help me. Where do I add language and language constants?

### Your environment
* version (AT/Framework)
* which browser and its version
* device(s) + operating system(s)

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by oliverfoster** [comment]
This plugin has no translatable parts.
Did you mean the Adapt Authoring Tool?

**Comment by alexkash** [comment]
I mean specifically the plugin. I converted everything to Adapt Authoring Tool, but when connecting plugins, in the course settings I can't find where to change the names of the fields, for example.
![image_2022_09_05T13_37_15_794Z](https://user-images.githubusercontent.com/2558467/188462933-fad70cae-93ac-4e8d-b627-2b111eefcc73.png)

**Comment by oliverfoster** [comment]
You have to write custom schemas. I think, I'm afraid there is no option to convert them at this stage. @taylortom could you verify?
