### ISSUE TITLE
Assessment Banks with Trickle Not Unlocking Next Article

### ISSUE THREAD

**Issue by marissa-champions** [adaptlearning/adapt-contrib-assessment#192]
### Subject of the issue/enhancement/features
Assessment with banks and trickle enabled does not unlock next section after assessment completion.

### Your environment
* framework 5.34.0/trickle 7.1.1/assessment 5.1.10/vanilla
* chrome
* macOS

### Steps to reproduce
Create a course with an assessment and banks and trickle enabled. 
Create an article below it. 
Complete assessment. 
Next article does not unlock.
Returning to menu and then returning to the page does show trickled content however.

### Expected behaviour
The second article should untrickle and unlock after the assessment is completed.

### Actual behaviour
The article does not unlock.

### Screenshots (if you can)
![chrome-capture-2024-2-27](https://github.com/adaptlearning/adapt-contrib-assessment/assets/60671690/9babe03b-2f3e-4015-98ec-a2fb5ceecf87)

**Comment by oliverfoster** [comment]
Can you try the two prs list about please?

**Comment by marissa-champions** [comment]
This fixes it for me! Thank you!

**Comment by oliverfoster** [comment]
Could you approve both please? 

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request
