### ISSUE TITLE
Authoring tool compatibility

### ISSUE THREAD

**Issue by dancgray** [adaptlearning/adapt-contrib-assessment#47]
_quizBankID attribute should be within an _assessment object.

Extensions attributes are usually held within an object named after the extension. e.g     

"_assessment": {
        "_postTotalScoreToLms": true,
        "_isPercentageBased": true,
        "_scoreToPass": 75,
        "_requireAssessmentPassed": true
    }

_quizBankID are specific to assessment plugin but are placed directly within the blocks in the readme and example.json.

They should be in an _assessment object within blocks.json.

**Comment by dancgray** [comment]
If _banks is enabled, blocks must be organised into questions banks by adding the _quizBankID attribute. We cannot validate for this in the authoring tool.

_quizBankID must start at 1 and increment by 1. In _split the position of the number in the list corresponds to the _quizBankID assigned in a block.

**Comment by dancgray** [comment]
_attempts can be a string (only infinite allowed) or a number. This element is currently defined as a number in the schema. We may need to change the schema type to a select and populate with ''infinite" and a number selection (if that's possible).

**Comment by moloko** [comment]
or maybe we could separate this out into a new property `_allowInfiniteAttempts`? 

Or allow `_attempts` to be left blank and assume infinite if it is?

**Comment by oliverfoster** [comment]
_attempts - will be infinite if the value is < 0 or null or undefined or "infinite". so a number is fine. just put the default as -1 and update the description to explain

**Comment by oliverfoster** [comment]
_quizBankIDs can be moved if it makes more logical sense? is there an authoring tool reason for it or just for convention?

**Comment by oliverfoster** [comment]
_quizBankIDs and _split. what's the easiest way to store split to allow it to validate? or is it simply that one is on the article and the other on the blocks?

**Comment by dancgray** [comment]
@oliverfoster the _attempts suggestion should work fine.

I think the convention for extension JSON in the authoring tool is to put it within an object to allow JSON to be added/removed when plugins are added/removed from courses. Would there be a code change in the assessment model to move this to _assessment._quizBankId in the block? 

It may be that validation is not possible without some custom validation for this plugin. I think we will need to re-address the authoring tool component inputs again as they are fairly lengthy now.

**Comment by oliverfoster** [comment]
Cool. yea a small set of changes i'd think. want me to do it before the schema gets accepted?
